import { Router } from "express";
import authUser from "../Middlewares/auth-middleware.js";
import * as controller from "../Controller/interview-controller.js"
import { uploade } from "../Middlewares/file-middleware.js";



const interviewRoutre = Router();


/**
 * @route /api/v1/initerview/generate-report
 * @method POST
 * @description "Use to generate interview report on the basis of user self description resumepdf and job description"
 * @access private
 */
interviewRoutre.post("/generate-report", authUser, uploade.single("resume"), controller.generateInterviewController)


/**
 * @route /api/v1/interview/ai-report/:id
 * @method GET
 * @description "Use to show interview report generated by ai to user; id is interview report id
 * @access private
 */
interviewRoutre.get("/ai-report/:id", authUser, controller.getReprotofUser);

/**
 * @route /api/v1/interview/all-ai-report
 * @method GET
 * @description "Use to show interview report generated by ai to user; id is interview report id
 * @access private
 */
interviewRoutre.get("/all-ai-report", authUser, controller.getAllReportOfUser);
// interviewRoutre.get("/all-ai-report", (req, res) => {
//     res.json({
//         success: true,
//         message: "All report route is working"
//     })
// });

/**
 * @route /api/v1/initerview/question/:id
 * @method GET
 * @description "Use to show interview report generated by ai to user; id is interview report id
 * @access private
 */
interviewRoutre.get("/questions/:id", authUser, controller.getQuestionsController);



export default interviewRoutre;